questions =  [
    // Republicanism right
    {"id": 0, "question": "Monarchy is an archaic system that has no place in the modern world.", "effects": {"right": 1}},
    {"id": 1, "question": "Republics are more effective.", "effects": {"right": 1}},
    {"id": 2, "question": "An absolute monarchy is worse than a dictatorship.", "effects": {"right": 1}},
    {"id": 3, "question": "Monarchism is inherently anti-nationalist.", "effects": {"right": 1}},
    {"id": 4, "question": "Billions of minds are better than one with a hat of gold.", "effects": {"right": 1}},
    {"id": 5, "question": "Monarchy is a decadent system which will eventually fall.", "effects": {"right": 1}},
    {"id": 6, "question": "Monarchs syphon taxpayers money to live without worries.", "effects": {"right": 1}},
    {"id": 7, "question": "Monarchies lead to the creation of an oppressive class of nobles.", "effects": {"right": 1}},
    {"id": 8, "question": "Communists are right in their anti-Monarchism.", "effects": {"right": 1}},
    {"id": 9, "question": "If I was a Monarch, I would abdicate my throne and establish a Free Republic.", "effects": {"right": 1}},
    {"id": 10, "question": "Even if in one case a Monarch is better than an leader elected by the people, I would still prefer the latter.", "effects": {"right": 1}},
    {"id": 11, "question": "A Republic is the only way to stay with the times, fulfill the needs of the nation, and not get stuck in the past.", "effects": {"right": 1}},
    {"id": 12, "question": "For man should be free and not shackled by the whims of someone else.", "effects": {"right": 1}},
    {"id": 13, "question": "The popularity of the Republican system isn't undeserved, for it gives a say to the unheard and oppressed.", "effects": {"right": 1}},
    {"id": 14, "question": "Monarchy leads to complacency.", "effects": {"right": 1}},
    // Monarchism left
    {"id": 15, "question": "The Monarch is the Father of the Nation.", "effects": {"right": -1}},
    {"id": 16, "question": "A country without a monarchy is like a body without a soul.", "effects": {"right": -1}},
    {"id": 17, "question": "Being against the monarchy is being against the nation.", "effects": {"right": -1}},
    {"id": 18, "question": "Monarchies tend to have better treatment of their citizens than republics.", "effects": {"right": -1}},
    {"id": 19, "question": "Monarchs are more responsible with their nations because they aren't 'renting' their countries.", "effects": {"right": -1}},
    {"id": 20, "question": "It was real Monarchism and it was glorious.", "effects": {"right": -1}},
    {"id": 21, "question": "Empires were better than the Nation-state.", "effects": {"right": -1}},
    {"id": 22, "question": "For a monarchy to work, one person needs to be wise; for a democracy to work, 51% of population needs to be wise; which is more likely?", "effects": {"right": -1}},
    {"id": 23, "question": "'No republic should ever be allowed to exist'.", "effects": {"right": -1}},
    {"id": 24, "question": "'Peace-loving' Republics have caused equally if not more suffering than all monarchies ever did.", "effects": {"right": -1}},
    {"id": 25, "question": "Without democracy, a society is nothing.", "effects": {"right": -1}},
    {"id": 26, "question": "The greatest slave of a Kingdom is the one who bears the crown.", "effects": {"right": -1}},
    {"id": 27, "question": "I would support a Monarchy for my country.", "effects": {"right": -1}},
    {"id": 28, "question": "The fruit of the Republics has grown bitter due to the blood of tyrants, despots, and innocents alike it has spilled.", "effects": {"right": -1}},
    {"id": 29, "question": "Whenever I hear 'Republic' I think of a bloodbath.", "effects": {"right": -1}},
    {"id": 30, "question": "I would give my live for the Monarch.", "effects": {"right": -1}},
    // Absolutism auth
    {"id": 31, "question": "L'etat, c'est moi.", "effects": {"auth": 1}},
    {"id": 32, "question": "The Monarch's reign is Chosen by God Himself.", "effects": {"auth": 1}},
    {"id": 33, "question": "A monarch should be obeyed even if he goes against God.", "effects": {"auth": 1}},
    {"id": 34, "question": "The French Revolution was a disaster to mankind.", "effects": {"auth": 1}},
    {"id": 35, "question": "Dissolve the Parliament!", "effects": {"auth": 1}},
    {"id": 36, "question": "Just because autocracy appears to exist less now, it doesn't mean it isn't a better system.", "effects": {"auth": 1}},
    {"id": 37, "question": "The reason democratic governments don't declare war on each other is because they are all puppets of the same globalist entity.", "effects": {"auth": 1}},
    {"id": 38, "question": "Equalizing the opinions of everyone on who should rule is destructive to the nation.", "effects": {"auth": 1}},
    {"id": 39, "question": "The peasants shouldn't get to choose their leaders.", "effects": {"auth": 1}},
    {"id": 40, "question": "If the King takes my wealth and kills my loved ones, I have no choice but to still be his subject.", "effects": {"auth": 1}},
    {"id": 41, "question": "A special noble class only stands in the way of a realm united under the monarch.", "effects": {"auth": 1}},
    {"id": 42, "question": "The Tree of Monarchism cannot grow fruit not because it has grown infertile, but because the Republicans poisoned the soil.", "effects": {"auth": 1}},
    {"id": 43, "question": "Monarchies of today are a joke, a shiny hat alone doesn't make one a monarch.", "effects": {"auth": 1}},
    {"id": 44, "question": "A paper stating what the Monarch or government can do is not only foolish but naive.", "effects": {"auth": 1}},
    {"id": 45, "question": "The Nobility should not exist as it divides the power instead of giving it to the monarch.", "effects": {"auth": 1}},
    {"id": 46, "question": "There are those who follow and those who lead.", "effects": {"auth": 1}},
    // Constitutionalism lib
    {"id": 47, "question": "The Monarch should only be a ceremonial figure for the Country to rally behind.", "effects": {"auth": -1}},
    {"id": 48, "question": "The Crown should protect the citizens from their own government.", "effects": {"auth": -1}},
    {"id": 49, "question": "One man having too much power would cause that power to be abused easily.", "effects": {"auth": -1}},
    {"id": 50, "question": "There are certain God given laws which no one should be able to limit or revoke.", "effects": {"auth": -1}},
    {"id": 51, "question": "The division of the powers within a state is necessary to avoid abuse of power.", "effects": {"auth": -1}},
    {"id": 52, "question": "The monarch is just another commoner with a title and a crown without the people behind him.", "effects": {"auth": -1}},
    {"id": 53, "question": "The Monarch should be protecting the constitution, and should not have power over it.", "effects": {"auth": -1}},
    {"id": 54, "question": "The Monarch should obey the law of the country just like everyone else, or face the consequences.", "effects": {"auth": -1}},
    {"id": 55, "question": "Monarchs should be held accountable to the people for their actions.", "effects": {"auth": -1}},
    {"id": 56, "question": "The King for the people, not the people for the King.", "effects": {"auth": -1}},
    {"id": 57, "question": "We should defend the constitution as it is what makes us free.", "effects": {"auth": -1}},
    {"id": 58, "question": "The People should never be oppressed by any institution.", "effects": {"auth": -1}},
    {"id": 59, "question": "Under no circumstances shall the Leader have unlimited Power.", "effects": {"auth": -1}},
    {"id": 60, "question": "Absolute power corrupts absolutely.", "effects": {"auth": -1}},
    // Merit prog
    {"id": 61, "question": "Merit decides the crown, not blood.", "effects": {"prog": 1}},
    {"id": 62, "question": "Wealth is the sign of nobility.", "effects": {"prog": 1}},
    {"id": 63, "question": "Even a commoner should be able to become a monarch.", "effects": {"prog": 1}},
    {"id": 64, "question": "Aristocracy should not be locked to certain families.", "effects": {"prog": 1}},
    {"id": 65, "question": "Technocratic Monarchy would be the best possible system.", "effects": {"prog": 1}},
    {"id": 66, "question": "Whether or not a person should be able to participate in politics should depend on the amount of studying he gave that field.", "effects": {"prog": 1}},
    {"id": 67, "question": "Inheritance should never be a thing, as it gives a person things he never worked for.", "effects": {"prog": 1}},
    {"id": 68, "question": "The best class in which its members are picked to rule the nation should be consistent of people who worked to be there.", "effects": {"prog": 1}},
    {"id": 69, "question": "Napoleon is a prime example on how merit triumphs over birthright.", "effects": {"prog": 1}},
    {"id": 70, "question": "The successor should be chosen by his qualifications, not by the time he was born.", "effects": {"prog": 1}},
    {"id": 71, "question": "It is unfair to deny someone a chance to rise in ranks based on their birthright.", "effects": {"prog": 1}},
    {"id": 72, "question": "A dynasty is just a family who had enough merit to rise to power.", "effects": {"prog": 1}},
    {"id": 73, "question": "We shouldn't idolize anyone just because what their forefathers did.", "effects": {"prog": 1}},
    {"id": 74, "question": "The reason Monarchy disappeared was because they weren't able to abandon the idea of Birthright.", "effects": {"prog": 1}},
    {"id": 75, "question": "The great empires of the world didn't come from the monarchist system but from the brilliance of its monarchs.", "effects": {"prog": 1}},
    {"id": 76, "question": "A.I. would make a great Monarch due to its intelligence.", "effects": {"prog": 1}},
    // Birthright trad
    {"id": 77, "question": "The Nation should have a heritage like a family, values passed on from father to child.", "effects": {"prog": -1}},
    {"id": 78, "question": "Inheritance must never be infringed upon.", "effects": {"prog": -1}},
    {"id": 79, "question": "Nobility is an essential class in a successful society.", "effects": {"prog": -1}},
    {"id": 80, "question": "The power passing from the father to the child is an inherently human system.", "effects": {"prog": -1}},
    {"id": 81, "question": "Nepotism is good, as it strengthens the familial structure of society.", "effects": {"prog": -1}},
    {"id": 82, "question": "Hereditary Monarchy is the better than Elective Monarchy, as the monarch would be trained for his role from birth.", "effects": {"prog": -1}},
    {"id": 83, "question": "Feudalism was a good system.", "effects": {"prog": -1}},
    {"id": 84, "question": "The Power should be set for someone to inherit and they shall be trained since birth to fit that role.", "effects": {"prog": -1}},
    {"id": 85, "question": "To have Succession secured is just as securing the future of the nation.", "effects": {"prog": -1}},
    {"id": 86, "question": "Serfs should be bound to the land they were born in.", "effects": {"prog": -1}},
    {"id": 87, "question": "Birthright is a sign of strength, for it shows a lineage of success.", "effects": {"prog": -1}},
    {"id": 88, "question": "It doesn't matter if a commoner proves he can do better than the monarch, he does not have royal blood.", "effects": {"prog": -1}},
    {"id": 89, "question": "Meritocracy is an unstable system because it doesn't secure the future but only the present.", "effects": {"prog": -1}},
    {"id": 90, "question": "We can never be sure merit is a sign of Goodness and Compassion, for those who are successful can cheat their way up.", "effects": {"prog": -1}},
    {"id": 91, "question": "It is such a great shame to see the great royal families being seen as nothing better than a citizen.", "effects": {"prog": -1}}
];
